# Generated by Django 5.2.14 on 2026-06-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobGridRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('customer', models.CharField(blank=True, max_length=255)),
                ('job_status', models.CharField(blank=True, choices=[('Job Active', 'Job Active'), ('Quoting in Progress', 'Quoting in Progress'), ('Quote Submitted', 'Quote Submitted'), ('Job Complete', 'Job Complete'), ('Project Lost', 'Project Lost'), ('Invoiced', 'Invoiced'), ('Unknown Status', 'Unknown Status')], default='Unknown Status', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('job_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('job_type', models.CharField(blank=True, max_length=100)),
                ('work_type', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('customer_contact', models.CharField(blank=True, max_length=255)),
                ('customer_po', models.CharField(blank=True, max_length=100)),
                ('customer_po_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lead', models.CharField(blank=True, max_length=255)),
                ('engineer_01', models.CharField(blank=True, max_length=255)),
                ('engineer_02', models.CharField(blank=True, max_length=255)),
                ('engineer_03', models.CharField(blank=True, max_length=255)),
                ('engineer_04', models.CharField(blank=True, max_length=255)),
                ('engineer_05', models.CharField(blank=True, max_length=255)),
                ('engineer_06', models.CharField(blank=True, max_length=255)),
                ('engineer_07', models.CharField(blank=True, max_length=255)),
                ('engineer_08', models.CharField(blank=True, max_length=255)),
                ('engineer_09', models.CharField(blank=True, max_length=255)),
                ('engineer_10', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Grid Row',
                'verbose_name_plural': 'Job Grid Rows',
                'ordering': ['sort_order', '-year', 'job_number'],
            },
        ),
    ]
