# Generated by Django 5.2.17 on 2026-08-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employeeprofile_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountNotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional name for this notification recipient.', max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Account Notification Recipient',
                'verbose_name_plural': 'Account Notification Recipients',
                'ordering': ['email'],
            },
        ),
    ]
