import logging
from pathlib import Path

from django.conf import settings
from django.core.files.base import ContentFile
from django.core.mail import EmailMessage
from django.core.mail.backends.smtp import EmailBackend
from django.utils import timezone

from ..models import (
    ApprovalNotificationRecipient,
    EmailConfiguration,
    Timesheet,
    TimesheetSubmissionArtifact,
)
from .exporter import build_timesheet_excel, build_timesheet_pdf
from .receipts_pdf import build_receipts_pdf_bytes, receipts_pdf_filename

logger = logging.getLogger(__name__)


def _employee_initials(user):
    full_name = user.get_full_name().strip()
    if full_name:
        return "".join(part[0].upper() for part in full_name.split() if part)
    return user.get_username()[:2].upper()


def _timesheet_url(timesheet):
    base_url = getattr(settings, "SITE_BASE_URL", "https://timetrack.ccswi.us").rstrip("/")
    return f"{base_url}{timesheet.get_absolute_url()}"


def _send_basic_email(*, config, subject, body, to):
    recipients = [email for email in to if email]
    if not recipients:
        return

    backend = _smtp_backend(config)
    message = EmailMessage(
        subject=subject,
        body=body,
        from_email=config.from_email,
        to=recipients,
        reply_to=[config.reply_to_email] if config.reply_to_email else None,
        connection=backend,
    )
    message.send()


def _approval_email_subject(timesheet):
    employee = timesheet.employee
    first_name = employee.first_name or ""
    last_name = employee.last_name or ""

    if not (first_name or last_name):
        name = employee.get_full_name() or employee.get_username()
    else:
        name = f"{first_name} {last_name}".strip()

    return f"{name} Timesheet {timesheet.week_start:%m/%d/%Y} - Time & Expense"


def _approval_email_body(timesheet):
    employee_name = timesheet.employee.get_full_name() or timesheet.employee.get_username()
    approved_by = timesheet.approved_by.get_full_name() if timesheet.approved_by else ""
    if timesheet.approved_by and not approved_by:
        approved_by = timesheet.approved_by.get_username()

    return "\n".join([
        "A timesheet has been approved.",
        "",
        f"Employee: {employee_name}",
        f"Week Start: {timesheet.week_start:%m/%d/%Y}",
        f"Approved By: {approved_by or '—'}",
        f"Approved At: {timezone.localtime(timesheet.approved_at):%m/%d/%Y %I:%M %p}" if timesheet.approved_at else "Approved At: —",
        "",
        "View Timesheet:",
        _timesheet_url(timesheet),
        "",
        "Attachments:",
        "- Excel Timesheet",
        "- PDF Timesheet",
        "- Receipts PDF",
    ])


def _smtp_backend(config):
    return EmailBackend(
        host=config.smtp_host,
        port=config.smtp_port,
        username=config.smtp_username or None,
        password=config.smtp_password or None,
        use_tls=config.use_tls,
        use_ssl=config.use_ssl,
        fail_silently=False,
    )


def send_test_email(config):
    if not config.test_recipient:
        raise ValueError("Test recipient is required.")

    backend = _smtp_backend(config)
    subject = "CCS Time Reporting - Test Email"
    body = "\n".join([
        "This is a test email generated by CCS Time Reporting.",
        "",
        f"Timestamp: {timezone.localtime(timezone.now()):%m/%d/%Y %I:%M:%S %p}",
        f"SMTP Host: {config.smtp_host}",
        f"From Address: {config.from_email}",
        f"Reply-To Address: {config.reply_to_email or '—'}",
        "",
        "If you received this email, email delivery is working correctly.",
    ])

    message = EmailMessage(
        subject=subject,
        body=body,
        from_email=config.from_email,
        to=[config.test_recipient],
        reply_to=[config.reply_to_email] if config.reply_to_email else None,
        connection=backend,
    )
    message.send()


def _save_generated_artifact(timesheet, generated_path, created_by, export_format):
    generated_path = Path(generated_path)
    file_type = "xlsx" if generated_path.suffix.lower() == ".xlsx" else "pdf"

    artifact = TimesheetSubmissionArtifact(
        timesheet=timesheet,
        file_type=file_type,
        export_format=export_format,
        created_by=created_by,
        submitted=True,
    )
    artifact.file.save(generated_path.name, ContentFile(generated_path.read_bytes()), save=True)
    return artifact


def _save_receipts_artifact(timesheet, receipts_bytes, filename, created_by):
    artifact = TimesheetSubmissionArtifact(
        timesheet=timesheet,
        file_type=TimesheetSubmissionArtifact.FileType.PDF,
        export_format=Timesheet.ExportFormat.PDF,
        created_by=created_by,
        submitted=True,
    )
    artifact.file.save(filename, ContentFile(receipts_bytes), save=True)
    return artifact


def send_timesheet_approved_email(timesheet, approved_by):
    """Generate approved timesheet attachments and email active approval recipients.

    Raises exceptions to the caller so the view can show a warning while keeping
    the approval itself successful.
    """
    config = EmailConfiguration.active_config()
    if not config:
        raise ValueError("No active email configuration exists.")

    recipients = list(
        ApprovalNotificationRecipient.objects.filter(active=True).values_list("email", flat=True)
    )
    if not recipients:
        raise ValueError("No active approval notification recipients exist.")

    timesheet = (
        Timesheet.objects
        .select_related("employee", "approved_by")
        .prefetch_related("receipts")
        .get(pk=timesheet.pk)
    )

    backend = _smtp_backend(config)
    subject = _approval_email_subject(timesheet)
    body = _approval_email_body(timesheet)

    message = EmailMessage(
        subject=subject,
        body=body,
        from_email=config.from_email,
        to=recipients,
        reply_to=[config.reply_to_email] if config.reply_to_email else None,
        connection=backend,
    )

    generated_attachments = []

    if timesheet.can_export_excel:
        excel_path = Path(build_timesheet_excel(timesheet))
        _save_generated_artifact(
            timesheet,
            excel_path,
            approved_by,
            Timesheet.ExportFormat.EXCEL,
        )
        generated_attachments.append((
            f"{_employee_initials(timesheet.employee)}_{timesheet.week_start:%Y%m%d}.xlsx",
            excel_path.read_bytes(),
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        ))

    pdf_path = Path(build_timesheet_pdf(timesheet))
    _save_generated_artifact(
        timesheet,
        pdf_path,
        approved_by,
        Timesheet.ExportFormat.PDF,
    )
    generated_attachments.append((
        f"{_employee_initials(timesheet.employee)}_{timesheet.week_start:%Y%m%d}_timesheet.pdf",
        pdf_path.read_bytes(),
        "application/pdf",
    ))

    receipts_bytes = build_receipts_pdf_bytes(timesheet)
    receipts_filename = receipts_pdf_filename(timesheet)
    _save_receipts_artifact(timesheet, receipts_bytes, receipts_filename, approved_by)
    generated_attachments.append((receipts_filename, receipts_bytes, "application/pdf"))

    for filename, content, mimetype in generated_attachments:
        message.attach(filename, content, mimetype)

    message.send()
    logger.info("Sent approved timesheet email for timesheet %s to %s", timesheet.pk, recipients)



def send_employee_timesheet_approved_email(timesheet, approved_by):
    config = EmailConfiguration.active_config()
    if not config:
        raise ValueError("No active email configuration exists.")

    if not timesheet.employee.email:
        raise ValueError("Employee does not have an email address.")

    approver = approved_by.get_full_name() or approved_by.get_username()
    subject = f"Timesheet Approved - Week of {timesheet.week_start:%m/%d/%Y}"
    body = "\n".join([
        f"Your timesheet for the week of {timesheet.week_start:%m/%d/%Y} has been approved.",
        "",
        f"Approved By: {approver}",
        "",
        "View Timesheet:",
        _timesheet_url(timesheet),
    ])

    _send_basic_email(
        config=config,
        subject=subject,
        body=body,
        to=[timesheet.employee.email],
    )


def send_employee_timesheet_rejected_email(timesheet, rejected_by, reason):
    config = EmailConfiguration.active_config()
    if not config:
        raise ValueError("No active email configuration exists.")

    if not timesheet.employee.email:
        raise ValueError("Employee does not have an email address.")

    rejector = rejected_by.get_full_name() or rejected_by.get_username()
    subject = f"Timesheet Rejected - Week of {timesheet.week_start:%m/%d/%Y}"
    body = "\n".join([
        f"Your timesheet for the week of {timesheet.week_start:%m/%d/%Y} was rejected.",
        "",
        f"Rejected By: {rejector}",
        "",
        "Reason:",
        reason or "No reason provided.",
        "",
        "View Timesheet:",
        _timesheet_url(timesheet),
        "",
        "Please make corrections and resubmit the timesheet.",
    ])

    _send_basic_email(
        config=config,
        subject=subject,
        body=body,
        to=[timesheet.employee.email],
    )


def send_timesheet_submitted_supervisor_email(timesheet, submitted_by):
    config = EmailConfiguration.active_config()
    if not config:
        raise ValueError("No active email configuration exists.")

    profile = getattr(timesheet.employee, "employee_profile", None)
    supervisor = getattr(profile, "supervisor", None) if profile else None

    if not supervisor:
        raise ValueError("Employee does not have a supervisor assigned.")

    if not supervisor.email:
        raise ValueError("Supervisor does not have an email address.")

    employee_name = timesheet.employee.get_full_name() or timesheet.employee.get_username()
    submitter = submitted_by.get_full_name() or submitted_by.get_username()

    subject = f"{employee_name} Timesheet {timesheet.week_start:%m/%d/%Y} - Submitted"
    body = "\n".join([
        f"{employee_name} has submitted a timesheet for approval.",
        "",
        f"Week Start: {timesheet.week_start:%m/%d/%Y}",
        f"Submitted By: {submitter}",
        "",
        "Review Timesheet:",
        _timesheet_url(timesheet),
    ])

    _send_basic_email(
        config=config,
        subject=subject,
        body=body,
        to=[supervisor.email],
    )

def send_timesheet_reopened_email(timesheet, reopened_by):
    config = EmailConfiguration.active_config()
    if not config:
        raise ValueError("No active email configuration exists.")

    recipients = list(
        ApprovalNotificationRecipient.objects.filter(active=True).values_list("email", flat=True)
    )
    if not recipients:
        raise ValueError("No active approval notification recipients exist.")

    employee_name = timesheet.employee.get_full_name() or timesheet.employee.get_username()
    reopened_name = reopened_by.get_full_name() or reopened_by.get_username()

    subject = f"{employee_name} Timesheet {timesheet.week_start:%m/%d/%Y} - Reopened"

    body = "\n".join([
        f"{employee_name}'s timesheet for week {timesheet.week_start:%m/%d/%Y} has been reopened for corrections.",
        "",
        f"Reopened By: {reopened_name}",
        "",
        "Reason:",
        timesheet.reopen_reason or "No reason provided.",
        "",
        "View Timesheet:",
        _timesheet_url(timesheet),
    ])

    _send_basic_email(
        config=config,
        subject=subject,
        body=body,
        to=recipients,
    )
