# Generated by ChatGPT for Parts Report support.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partentry",
            name="job",
        ),
        migrations.RemoveField(
            model_name="partentry",
            name="timesheet",
        ),
        migrations.RemoveField(
            model_name="partentry",
            name="unit_cost",
        ),
        migrations.RemoveField(
            model_name="partentry",
            name="work_date",
        ),
        migrations.RemoveField(
            model_name="partentry",
            name="description",
        ),
        migrations.RemoveField(
            model_name="partentry",
            name="part_number",
        ),
        migrations.AddField(
            model_name="partentry",
            name="additional_notes_for_customer",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="partentry",
            name="ee_stock_job_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="partentry",
            name="part_description_part_number",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="partentry",
            name="reorder_part",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="partentry",
            name="time_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="part_entry",
                to="timesheets.timeentry",
            ),
        ),
        migrations.AlterModelOptions(
            name="partentry",
            options={
                "verbose_name": "Part entry",
                "verbose_name_plural": "Part entries",
            },
        ),
    ]
