# Generated by Django 5.2.14 on 2026-05-27 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_update_partentry_for_parts_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partentry',
            name='unit_cost_currency',
        ),
    ]
