# Generated by ChatGPT for job status/invoice dropdown choices.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0009_expand_job_master"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Job Active", "Job Active"),
                    ("Quoting in Progress", "Quoting in Progress"),
                    ("Quote Submitted", "Quote Submitted"),
                    ("Job Complete", "Job Complete"),
                    ("Project Lost", "Project Lost"),
                    ("Invoiced", "Invoiced"),
                    ("Unknown Status", "Unknown Status"),
                ],
                default="Unknown Status",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="invoice_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("Final", "Final"),
                    ("Invoiced", "Invoiced"),
                    ("None", "None"),
                    ("None per ML", "None per ML"),
                    ("Progress", "Progress"),
                ],
                max_length=100,
            ),
        ),
    ]
