# Generated by Django 5.2.14 on 2026-06-25 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0012_job_list_import'),
        ('timesheets', '0012_job_people_users'),
    ]

    operations = [
    ]
