# Generated by Django 5.2.15 on 2026-07-09 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0014_job_engineer_users_timesheetreopenrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='engineer_users',
            field=models.ManyToManyField(blank=True, related_name='engineering_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
