# Generated by Django 5.2.15 on 2026-07-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0015_job_engineer_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetreopenrequest',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=10),
        ),
    ]
