# Generated by Django 5.2.15 on 2026-07-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0016_timesheetreopenrequest_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetreopenrequest',
            name='decision_notes',
            field=models.TextField(blank=True),
        ),
    ]
