# Generated by Django 5.2.17 on 2026-09-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0020_jobuseralias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailjob',
            name='job_type',
            field=models.CharField(choices=[('timesheet_approved_admin', 'Timesheet Approved - Admin'), ('timesheet_approved_employee', 'Timesheet Approved - Employee'), ('timesheet_rejected_employee', 'Timesheet Rejected - Employee'), ('timesheet_submitted_supervisor', 'Timesheet Submitted - Supervisor'), ('timesheet_reopen_request', 'Timesheet Reopen Request'), ('timesheet_reopened_admin', 'Timesheet Reopened - Admin'), ('timesheet_reopen_approved_employee', 'Timesheet Reopen Approved - Employee'), ('timesheet_reopen_rejected_employee', 'Timesheet Reopen Rejected - Employee')], max_length=50),
        ),
    ]
