# Generated by Django 5.2.17 on 2026-10-02 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0021_alter_emailjob_job_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='quickbooks_exported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='quickbooks_exported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quickbooks_exported_timesheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reopened', 'Reopened'), ('approved', 'Approved'), ('exported_to_quickbooks', 'Exported to QuickBooks'), ('invoiced', 'Invoiced'), ('rejected', 'Rejected'), ('void', 'Voided')], default='draft', max_length=30),
        ),
    ]
